env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/react"
  - "prettier/@typescript-eslint"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules: {
  "@typescript-eslint/no-explicit-any": "off",
  "@typescript-eslint/camelcase": "off",
  "@typescript-eslint/no-unused-vars": "off"
}
